Docstrings for `set_aog_theme!` and `aog_theme`
JuliaPlots/AlgebraOfGraphics.jl pull request #347
Opened 2022-02-11 10:03 UTC by KronosTheLate

What it says on the box.

2022-02-14 11:35 UTC, piever requested changes

2022-02-14 11:35 UTC, piever commented on src/theme.jl
> +Returns a `NamedTuple` of theme settings. Intended for internal use.
```suggestion
Return a `NamedTuple` of theme settings. Intended for internal use.
```

2022-02-14 11:35 UTC, piever commented on src/theme.jl
> +exported).
```suggestion
as defined by the unexported internal function [`AlgebraOfGraphics.aog_theme`](@ref).
```

2022-02-14 11:35 UTC, piever commented on src/theme.jl
> +see the example below.
```suggestion
To tweak the predefined theme, use the function `Makie.update_theme!`.
See the example below on how to change, e.g., default fontsize, title, and markersize.
```

2022-02-14 11:35 UTC, piever commented on src/theme.jl
> +The provided functionality is exposed to the user by the function `set_aog_theme!`.
```suggestion
The provided functionality is exposed to the user by the function [`set_aog_theme!`](@ref).
```

2022-02-14 11:35 UTC, piever commented on src/theme.jl
> +For more information about setting themes, see the `theming`
```suggestion
For more information about setting themes, see the `Theming`
```

2022-02-14 11:35 UTC, piever commented on src/theme.jl
> +)
```suggestion
update_theme!(                  # Tweaks the current theme
    fontsize=30,
    markersize=40,
    Axis=(title="MyDefaultTitle",)
)
```

2022-02-14 11:40 UTC, piever commented
Thanks for the PR! I've added some comments mostly about wording / style. For CI to pass, the docstrings will need to be included in the documentation website. I imagine the most reasonable place for them would be a `Theming` subsection [here](http://juliaplots.org/AlgebraOfGraphics.jl/dev/API/functions/). They could probably also be referenced [here](http://juliaplots.org/AlgebraOfGraphics.jl/dev/layers/draw/), but that can be done in a separate PR.

2022-02-15 15:31 UTC, KronosTheLate commented
Nice! Your suggestions were all improvements in my eyes too, thanks.

It will be some time before I find the time to add a theming section, and I do not have all that much to say about it. Is it something that you would be okay with implementing?

2022-02-18 18:02 UTC, piever requested changes

2022-02-18 18:02 UTC, piever commented on src/theme.jl
> +julia> using GLMakie
```suggestion
julia> using CairoMakie
```

The AlgebraOfGraphics docs always use CairoMakie.

2022-02-18 18:02 UTC, piever commented on docs/src/API/functions.md
> +Note that the function `update_theme!` is not defined by AlgebraOfGraphics.jl, but by whatever Makie backend you are using.
```suggestion
AlgebraOfGraphics.aog_theme
```

I think it's fine to document internal functions (this is the API section, so it should be quite thorough). At most, it could go in the `## Internals` section, but I think it's fine to keep it here. IMO, the comment on `update_theme!` is probably not needed, because the docstring refers to `Makie.update_theme!`, so it should be clear that it comes from Makie.

In any case, the comment should to be out of the

````md
```@docs

```
````

block, otherwise I think Documenter errors (it tries to look up every word as if it had a docstring).

2022-02-20 17:30 UTC, piever approved these changes

2022-02-20 17:30 UTC, merged