Clarify documentation of custom scales
JuliaPlots/AlgebraOfGraphics.jl pull request #354
Opened 2022-02-22 15:57 UTC by haberdashPI

Based on discussion from #329

2022-02-24 13:42 UTC, piever requested changes

2022-02-24 13:42 UTC, piever commented on docs/gallery/gallery/scales/custom_scales.jl
> +# to [Visual](@ref). Using `pallettes` for a discrete scale goes from being
```suggestion
# to [Visual](@ref). Using `palettes` for a discrete scale goes from being
```

2022-02-24 13:42 UTC, piever commented on docs/gallery/gallery/scales/custom_scales.jl
> +#    directly from Makie, while `pallettes` is used by AlgebraOfGraphics
```suggestion
#    directly from Makie, while `palettes` is used by AlgebraOfGraphics
```

2022-02-24 13:48 UTC, piever commented
Thanks, this is very helpful! Looks good to me other than a couple of typos.

2022-02-24 14:09 UTC, haberdashPI commented
I made a few changes, that I think will improve clarity, based on my slightly improved understanding. I'm going to also add a cross reference under the colormap section.

2022-02-24 16:10 UTC, piever commented on docs/gallery/gallery/scales/custom_scales.jl
> +# manually specify the palette used for a particular attribute
```suggestion
# sensible default palettes for many attributes. In either case, you can always
# manually specify the palette used for a particular attribute.
```

2022-02-24 16:10 UTC, piever commented on docs/gallery/gallery/scales/custom_scales.jl
> +#    defined for an entire figure, while palettes can vary by layer.
I may have been confusing in the explanation in #329: I meant that palettes are global (they are enforced to match on all layers) whereas things given as `visual` can be specific to a layer, so I'm not particularly fond of the idea of passing global information (such as colorschemes/colormaps) to `visual`: it leads to some odd logic to figure out the global colormap from a bunch of attributes in different layers. Probably better to just omit this sentence for now.

2022-02-24 16:43 UTC, haberdashPI commented on docs/gallery/gallery/scales/custom_scales.jl
> +#    defined for an entire figure, while palettes can vary by layer.
Ah, okay, I see. That makes sense. I'll revise.

2022-02-24 18:03 UTC, piever requested changes

2022-02-24 18:03 UTC, piever commented on docs/src/generated/visual.jl
> +#    Scales)
```suggestion
#    you will want to instead use the related notion of a [palette](@ref Custom
#    Scales).
```

It also looks like Documenter cannot find the reference (doc build is failing).

2022-02-24 18:03 UTC, piever commented on docs/gallery/gallery/scales/custom_scales.jl
> +
```suggestion
```

Just to be sure the conversion to markdown does not screw up the note formatting.

2022-03-15 10:48 UTC, piever approved these changes

2022-03-15 10:51 UTC, merged